#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    pwrEx,          sensorAnalog)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           rightD,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightU,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           launcherR,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port5,           roller,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           launcherL,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port7,           leftU,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftD,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

#include "include/DriveSys.h"
#include "include/IntakeSys.h"
#include "include/LauncherSys.h"
#include "include/JoySys.h"

void pre_auton()
{
	bLCDBacklight = true;
	//call init code for all systems
  drInit();
  lrInit();
  joyInit();
  //intake system requires no init for now...
}

task autonomous()
{
	//set the launcher speed to fullcourt
	lrState.launcherSpeed = getMotorSpeedFromEnum(FULLCOURT);
	//turn the intake on
	inState.runIntake = true;
	inState.runRoller = true;
}

void displayBattery() {
	clearLCDLine(0);
	clearLCDLine(1);
	string expanderDisplay;
	stringFormat(expanderDisplay, "Expander Voltage: %f", SensorValue[pwrEx] / 275);
	displayLCDCenteredString(1, expanderDisplay);
}

task usercontrol()
{
	//reset state from autonomous mode
	lrState.launcherSpeed = getMotorSpeedFromEnum(NONE);
	inState.runIntake = false;
	inState.runRoller = true;
	while (true) {
		//displayBattery();
		//grab our input
		joyPollInput();
  		//drive system
		drPollInput();
		drApply();
		//intake system
		inPollInput();
		inApply();
		//launcher system
		lrCalculateDelta();
		lrPollInput();
		lrApply();
		wait1Msec(100);
	}
}
